### ISSUE TITLE
Inconsistency of contextual variables(For ex: 'dict')

### ISSUE THREAD

**Issue by ynikulin** [semirook/snaql#3]
**test/test.sql**
```
{% sql 'test' %}
    {{ var }}
{% endsql %}
```

**test.py**
```
from snaql.factory import Snaql
import os

ql_factory = Snaql(os.path.abspath(os.path.dirname(__file__)), 'test')
queries = ql_factory.load_queries('test.sql')
print "List:", queries.test(**{'var': [1, 2, 3]})  # Good
print "Dict:", queries.test(**{'var': {"root": 1}})  # Bad
```
**Result**
List: [1, 2, 3]
Dict: ['root']

**Comment by semirook** [comment]
It is normal behavior of Jinja2 template engine and not a Snaql issue.

**Comment by ynikulin** [comment]
I'm not often use Ninja (or some temlate engine) but: 

```
from jinja2 import Environment
from jinja2.loaders import DictLoader

print "List: ", Environment().from_string("{{ var }}").render(**{'var': [1, 2, 3]})
print "Dict: ", Environment().from_string("{{ var }}").render(**{'var': {"root": 1}})
```

**Result**
List: [1, 2, 3]
Dict: {'root': 1}

Or i do something wrong :)

**Comment by semirook** [comment]
Holy shit, it's true! 
I don't know why you need it, but it's fixed.

**Comment by ynikulin** [comment]
I debug issue, look at:
https://github.com/semirook/snaql/blob/master/snaql/factory.py#L205
https://github.com/semirook/snaql/blob/master/snaql/factory.py#L206

Cool library ;)

**Comment by ynikulin** [comment]
Ok )
