### ISSUE TITLE
Is there a way to get a printed query formatted with the original line breaks?

### ISSUE THREAD

**Issue by fredthedead** [semirook/snaql#6]
When 'generating' and printing a query it comes out 'flattened', all line breaks are removed and the query is just a single line.

For example this:
`
{% sql 'select_all' %}
    SELECT *
    FROM news
{% endsql %}
`

becomes:
`SELECT * FROM news`

Is there a way to preserve the formatting/line breaks as defined in the .sql file?

**Comment by semirook** [comment]
@fredthedead can you tell me why you need this? Resulting string representation is just for DB query and doesn't have to save formatting. Maybe I can provide some special method for that... but why?

**Comment by fredthedead** [comment]
Two main reasons are:
1. Single lines comments break the query. For example:
```
select *
-- some comment
from my_table
```
turns to:
`select * -- some comment from my_table` ('from my_table' is now commented out too)

2. To be able to check the query before it runs or after it fails. I am running the queries using SQLAlchemy and if there's an error it dumps the query in the same format it was provided... having it printed in a single line makes it very hard to debug what went wrong and where.

**Comment by semirook** [comment]
Ok, it's done for you. Hope it's really helpful for you.
